// <auto-generated />
using ExpenseTracker.Core.Transactions.Model;
using ExpenseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ExpenseTracker.Migrations
{
    [DbContext(typeof(ExpenseTrackerContext))]
    [Migration("20180415150106_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ExpenseTracker.Core.Tags.Model.KeyPhrase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("TagId");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("KeyPhrases");
                });

            modelBuilder.Entity("ExpenseTracker.Core.Tags.Model.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ExpenseTracker.Core.Transactions.Model.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Details");

                    b.Property<int?>("TagId");

                    b.Property<int>("TransactionType");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseTracker.Core.Tags.Model.KeyPhrase", b =>
                {
                    b.HasOne("ExpenseTracker.Core.Tags.Model.Tag")
                        .WithMany("KeyPhrases")
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("ExpenseTracker.Core.Transactions.Model.Transaction", b =>
                {
                    b.HasOne("ExpenseTracker.Core.Tags.Model.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");
                });
#pragma warning restore 612, 618
        }
    }
}
